package com.dayapp.domain;

import java.time.LocalDateTime;

public class BusinessDays {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_days.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_days.id_days
     *
     * @mbg.generated
     */
    private Integer idDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_days.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_days.day
     *
     * @mbg.generated
     */
    private String day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_days.created
     *
     * @mbg.generated
     */
    private LocalDateTime created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_days.modified
     *
     * @mbg.generated
     */
    private LocalDateTime modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_days.id
     *
     * @return the value of business_days.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_days.id
     *
     * @param id the value for business_days.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_days.id_days
     *
     * @return the value of business_days.id_days
     *
     * @mbg.generated
     */
    public Integer getIdDays() {
        return idDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_days.id_days
     *
     * @param idDays the value for business_days.id_days
     *
     * @mbg.generated
     */
    public void setIdDays(Integer idDays) {
        this.idDays = idDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_days.name
     *
     * @return the value of business_days.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_days.name
     *
     * @param name the value for business_days.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_days.day
     *
     * @return the value of business_days.day
     *
     * @mbg.generated
     */
    public String getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_days.day
     *
     * @param day the value for business_days.day
     *
     * @mbg.generated
     */
    public void setDay(String day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_days.created
     *
     * @return the value of business_days.created
     *
     * @mbg.generated
     */
    public LocalDateTime getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_days.created
     *
     * @param created the value for business_days.created
     *
     * @mbg.generated
     */
    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_days.modified
     *
     * @return the value of business_days.modified
     *
     * @mbg.generated
     */
    public LocalDateTime getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_days.modified
     *
     * @param modified the value for business_days.modified
     *
     * @mbg.generated
     */
    public void setModified(LocalDateTime modified) {
        this.modified = modified;
    }
}