package com.dayapp.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.dayapp.domain.BusinessDays;

@Mapper
public interface BusinessDaysMapper {


	List<BusinessDays> selectAll();

	List<BusinessDays> selectByIdDays(Integer keyword);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_days
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_days
     *
     * @mbg.generated
     */
    int insert(BusinessDays record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_days
     *
     * @mbg.generated
     */
    int insertSelective(BusinessDays record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_days
     *
     * @mbg.generated
     */
    BusinessDays selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_days
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BusinessDays record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_days
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BusinessDays record);

}